packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - bufferutil
  - core-js
  - esbuild

catalogs:
  default:
    # Core dependencies
    zod: '^4.3.6'
    typescript: '^5.9.3'

    # React ecosystem
    react: '^19.2.4'
    react-dom: '^19.2.4'
    '@types/react': '^19.2.14'
    '@types/react-dom': '^19.2.3'

    # Build tools
    vite: '^7.3.1'
    '@vitejs/plugin-react': '^5.1.4'

    # TanStack
    '@tanstack/react-db': '^0.1.70'
    '@tanstack/react-query': '^5.90.21'
    '@tanstack/react-router': '^1.159.10'
    '@tanstack/react-router-ssr-query': '^1.159.10'
    '@tanstack/react-start': '^1.159.11'
    '@tanstack/router-plugin': '^1.159.11'
    '@tanstack/db': '^0.5.26'
    '@tanstack/electric-db-collection': '^0.2.33'
    '@tanstack/query-db-collection': '^1.0.23'

    # TanStack DevTools
    '@tanstack/devtools-vite': '^0.3.12'
    '@tanstack/react-devtools': '^0.8.6'
    '@tanstack/react-query-devtools': '^5.91.3'
    '@tanstack/react-router-devtools': '^1.159.10'

    # Database
    drizzle-orm: '^0.45.1'
    '@neondatabase/serverless': '^1.0.2'

    # Auth
    better-auth: '^1.4.18'

    # Sync
    '@electric-sql/client': '^1.5.5'

    # Storage
    '@aws-sdk/client-s3': '^3.990.0'
    '@aws-sdk/s3-request-presigner': '^3.990.0'

    # UI - Radix
    '@radix-ui/react-avatar': '^1.1.11'
    '@radix-ui/react-checkbox': '^1.3.3'
    '@radix-ui/react-dialog': '^1.1.15'
    '@radix-ui/react-dropdown-menu': '^2.1.16'
    '@radix-ui/react-label': '^2.1.8'
    '@radix-ui/react-progress': '^1.1.8'
    '@radix-ui/react-scroll-area': '^1.2.10'
    '@radix-ui/react-select': '^2.2.6'
    '@radix-ui/react-separator': '^1.1.8'
    '@radix-ui/react-slider': '^1.3.6'
    '@radix-ui/react-slot': '^1.2.4'
    '@radix-ui/react-tabs': '^1.1.13'
    '@radix-ui/react-toggle': '^1.1.10'
    '@radix-ui/react-toggle-group': '^1.1.11'

    # UI - Utilities
    class-variance-authority: '^0.7.1'
    clsx: '^2.1.1'
    tailwind-merge: '^3.4.0'
    tailwindcss-animate: '^1.0.7'
    lucide-react: '^0.559.0'
    motion: '^12.34.0'
    sonner: '^2.0.7'

    # Forms
    react-hook-form: '^7.71.1'
    '@hookform/resolvers': '^5.2.2'

    # Styling
    tailwindcss: '^4.1.18'
    '@tailwindcss/vite': '^4.1.18'
    tw-animate-css: '^1.4.0'

    # Types
    '@types/node': '^25.2.3'
    '@types/pg': '^8.16.0'
    '@types/ws': '^8.18.1'

    # ESLint/Prettier
    eslint: '^9.39.2'
    '@eslint/js': '^9.39.2'
    eslint-config-prettier: '^10.1.8'
    eslint-plugin-jsx-a11y: '^6.10.2'
    eslint-plugin-n: '^17.23.2'
    eslint-plugin-react: '^7.37.5'
    eslint-plugin-react-hooks: '^7.0.1'
    eslint-plugin-simple-import-sort: '^12.1.1'
    eslint-plugin-turbo: '^2.5.0'
    prettier: '^3.8.1'
    typescript-eslint: '^8.55.0'

    # Build utilities
    ts-morph: '^27.0.2'
    tsx: '^4.21.0'

    # UUID
    uuid: '^13.0.0'
