/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedScoresRouteImport } from './routes/_authenticated/scores'
import { Route as AuthenticatedScoresIndexRouteImport } from './routes/_authenticated/scores.index'
import { Route as ApiSyncSplatRouteImport } from './routes/api/sync.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthenticatedScoresSongIdRouteImport } from './routes/_authenticated/scores.$songId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScoresRoute = AuthenticatedScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScoresIndexRoute =
  AuthenticatedScoresIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedScoresRoute,
  } as any)
const ApiSyncSplatRoute = ApiSyncSplatRouteImport.update({
  id: '/api/sync/$',
  path: '/api/sync/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScoresSongIdRoute =
  AuthenticatedScoresSongIdRouteImport.update({
    id: '/$songId',
    path: '/$songId',
    getParentRoute: () => AuthenticatedScoresRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/scores': typeof AuthenticatedScoresRouteWithChildren
  '/scores/$songId': typeof AuthenticatedScoresSongIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sync/$': typeof ApiSyncSplatRoute
  '/scores/': typeof AuthenticatedScoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/scores/$songId': typeof AuthenticatedScoresSongIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sync/$': typeof ApiSyncSplatRoute
  '/scores': typeof AuthenticatedScoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/_authenticated/scores': typeof AuthenticatedScoresRouteWithChildren
  '/_authenticated/scores/$songId': typeof AuthenticatedScoresSongIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sync/$': typeof ApiSyncSplatRoute
  '/_authenticated/scores/': typeof AuthenticatedScoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/scores'
    | '/scores/$songId'
    | '/api/auth/$'
    | '/api/sync/$'
    | '/scores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/scores/$songId'
    | '/api/auth/$'
    | '/api/sync/$'
    | '/scores'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/profile'
    | '/_authenticated/scores'
    | '/_authenticated/scores/$songId'
    | '/api/auth/$'
    | '/api/sync/$'
    | '/_authenticated/scores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSyncSplatRoute: typeof ApiSyncSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/scores': {
      id: '/_authenticated/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof AuthenticatedScoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scores/': {
      id: '/_authenticated/scores/'
      path: '/'
      fullPath: '/scores/'
      preLoaderRoute: typeof AuthenticatedScoresIndexRouteImport
      parentRoute: typeof AuthenticatedScoresRoute
    }
    '/api/sync/$': {
      id: '/api/sync/$'
      path: '/api/sync/$'
      fullPath: '/api/sync/$'
      preLoaderRoute: typeof ApiSyncSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/scores/$songId': {
      id: '/_authenticated/scores/$songId'
      path: '/$songId'
      fullPath: '/scores/$songId'
      preLoaderRoute: typeof AuthenticatedScoresSongIdRouteImport
      parentRoute: typeof AuthenticatedScoresRoute
    }
  }
}

interface AuthenticatedScoresRouteChildren {
  AuthenticatedScoresSongIdRoute: typeof AuthenticatedScoresSongIdRoute
  AuthenticatedScoresIndexRoute: typeof AuthenticatedScoresIndexRoute
}

const AuthenticatedScoresRouteChildren: AuthenticatedScoresRouteChildren = {
  AuthenticatedScoresSongIdRoute: AuthenticatedScoresSongIdRoute,
  AuthenticatedScoresIndexRoute: AuthenticatedScoresIndexRoute,
}

const AuthenticatedScoresRouteWithChildren =
  AuthenticatedScoresRoute._addFileChildren(AuthenticatedScoresRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedScoresRoute: typeof AuthenticatedScoresRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedScoresRoute: AuthenticatedScoresRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSyncSplatRoute: ApiSyncSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
